import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },

];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "The Girl Who Fell from the Sky",
    price: "3100",
    color: "a memoir",
    brand: "Lenscart",
    badge: true,
    des: "From a terrible accident that left her paraplegic, Emma Carey has become an inspiration for hundreds of thousands online to live life to the fullest and remind us that if we can, we must. There on that helicopter, somewhere over Switzerland on a Sunday in June, came the first tiny whisper. A voice that would carry me for years to come. 'I'm going to be ok. There's still joy here.' When Emma Carey was twenty, she fell from 14,000 feet and survived. In The Girl Who Fell From the Sky Emma tells us the inspirational story of how, through one of her greatest tragedies, she found her truest self. From waking in the hospital a paraplegic to learning how to use her legs again, through the six-year long court case and now being finally free to make the most of her life, Emma teaches us the importance of courage and resilience.",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "Serafina and the Black Cloak",
    price: "1500",
    color: "Fantasy, Historical Fiction",
    brand: "Fastrack", // Added brand information
    badge: true,
    des: "Serafina has never had a reason to disobey her pa and venture beyond the grounds of the Biltmore estate. There’s plenty to explore in her grand home, although she must take care to never be seen. None of the rich folk upstairs know that Serafina exists; she and her pa, the estate’s maintenance man, have secretly lived in the basement for as long as Serafina can remember.",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Christopher Robin",
    price: "2150",
    color: "Drama/Family",
    brand: "Ray-Ban", // Added brand information
    badge: true,
    des: "Christopher Robin -- now a family man living in London -- receives a surprise visit from his old childhood pal, Winnie-the-Pooh. With Christopher's help, Pooh embarks on a journey to find his friends -- Tigger, Eeyore, Owl, Piglet, Rabbit, Kanga and Roo. Once reunited, the lovable bear and the gang travel to the big city to help Christopher rediscover the joy of life.",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "The Intended(A Culling of Blood and Magic)",
    price: "1200",
    color: "Fantasy Romance,Paranormal Romance",
    brand: "SPeter Jones", // Added brand information
    badge: true,
    des: "Emery may have survived the Culling, but now she’s on the run. Forced to find her way in a world of magic behind the wards of New Orleans, Emery struggles to accept her newfound identity as a witch and a mother. Her coven is demanding that she choose between the magic she’s always wanted and the child she already loves.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: spfOne,
    productName: "The Girl Who Fell from the Sky",
    price: "3100",
    color: "a memoir",
    badge: true,
    des: "From a terrible accident that left her paraplegic, Emma Carey has become an inspiration for hundreds of thousands online to live life to the fullest and remind us that if we can, we must. There on that helicopter, somewhere over Switzerland on a Sunday in June, came the first tiny whisper. A voice that would carry me for years to come. 'I'm going to be ok. There's still joy here.' When Emma Carey was twenty, she fell from 14,000 feet and survived. In The Girl Who Fell From the Sky Emma tells us the inspirational story of how, through one of her greatest tragedies, she found her truest self. From waking in the hospital a paraplegic to learning how to use her legs again, through the six-year long court case and now being finally free to make the most of her life, Emma teaches us the importance of courage and resilience.",
  },
  {
    _id: 1002,
    img: spfTwo,
    productName: "Serafina and the Black Cloak",
    price: "1500",
    color: "Fantasy, Historical Fiction",
    badge: true,
    des: "Serafina has never had a reason to disobey her pa and venture beyond the grounds of the Biltmore estate. There’s plenty to explore in her grand home, although she must take care to never be seen. None of the rich folk upstairs know that Serafina exists; she and her pa, the estate’s maintenance man, have secretly lived in the basement for as long as Serafina can remember.",
  },
  {
    _id: 1003,
    img: spfThree,
    productName: "Christopher Robin",
    price: "2150",
    color: "Drama/Family",
    badge: true,
    des: "Christopher Robin -- now a family man living in London -- receives a surprise visit from his old childhood pal, Winnie-the-Pooh. With Christopher's help, Pooh embarks on a journey to find his friends -- Tigger, Eeyore, Owl, Piglet, Rabbit, Kanga and Roo. Once reunited, the lovable bear and the gang travel to the big city to help Christopher rediscover the joy of life.",
  },
  {
    _id: 1004,
    img: spfFour,
    productName: "The Intended(A Culling of Blood and Magic)",
    price: "1200",
    color: "Fantasy Romance,Paranormal Romance",
    badge: true,
    des: "Emery may have survived the Culling, but now she’s on the run.Forced to find her way in a world of magic behind the wards of New Orleans, Emery struggles to accept her newfound identity as a witch and a mother. Her coven is demanding that she choose between the magic she’s always wanted and the child she already loves. ",
  },
  {
    _id: 1005,
    img: bestSellerOne,
    productName: "Game Of Thrones(The Complete Series)",
    price: "2100",
    color: "Fantasy drama",
    badge: true,
    des: "Trouble is brewing in Westeros. For the inhabitants of this world, control of the Iron Throne holds the lure of great power. But in a land where seasons can last a lifetime, winter is coming...and beyond the Great Wall that protects them, a forgotten evil has returned. HBO presents this epic series based on the book series A Song of Ice and Fire by George R.R. Martin.",
  },
  {
    _id: 1006,
    img: bestSellerTwo,
    productName: "Hunger games the ballad of songbirds and snakes",
    price: "2100",
    color: "Gray",
    badge: false,
    des: "The story of Coriolanus Snow, years before he would become the tyrannical President of Panem. He is handsome and charming, and though the Snow family has fallen on hard times, Coriolanus sees a chance for a change in his fortunes when he is chosen to be a mentor for the 10th Hunger Games only to have his elation dashed when he is assigned to mentor a girl tribute named Lucy Gray Baird from the impoverished District 12."
  },
  {
    _id: 1007,
    img: bestSellerThree,
    productName: "Harry potter and sorcerer's stone ",
    price: "1300",
    color: "Fantasy film",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1008,
    img: bestSellerFour,
    productName: "The mans at the ruins film type ",
    price: "1600",
    color: "Natural horror",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1009,
    img: newArrOne,
    productName: "The Wise Man's Fear",
    price: "1500",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1010,
    img: newArrTwo,
    productName: "Percy Jackson: Sea of Monsters",
    price: "1500",
    color: "Adventure/Fantasy",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1011,
    img: newArrThree,
    productName: "Three Men in a Boat",
    price: "1800",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1012,
    img: newArrFour,
    productName: "Bret Easton Ellis",
    price: "2000",
    color: "Transgressive fiction",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1013,
    img: newArrTwo,
    productName: "Serafina and the Black Cloak",
    price: "1200",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },

  
  {
    _id: 1015,
    img: newArrFour,
    productName: "Percy Jackson: Sea of Monsters",
    price: "1500",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
 
  {
    _id: 1017,
    img: bestSellerFour,
    productName: "The Wise Man's Fear",
    price: "1500",
    color: "Black",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1018,
    img: newArrOne,
    productName: "Bret Easton Ellis",
    price: "1500",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  
  {
    _id: 1020,
    img: newArrThree,
    productName: "Serafina and the Black Cloak",
    price: "1500",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1021,
    img: spfThree,
    productName: "Hunger games the ballad of songbirds and snakes",
    price: "1500",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1022,
    img: spfFour,
    productName: "The Intended(A Culling of Blood and Magic)",
    price: "1500",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1023,
    img: bestSellerOne,
    productName: "Serafina and the Black Cloak",
    price: "1500",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1024,
    img: spfOne,
    productName: "Bret Easton Ellis",
    price: "1500",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1025,
    img: spfTwo,
    productName: "The Intended(A Culling of Blood and Magic)",
    price: "1500",
    color: "Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1026,
    img: spfThree,
    productName: "Signa Unisex Eyeglasses",
    price: "1500",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1027,
    img: spfFour,
    productName: "The Wise Man's Fear",
    price: "1500",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1028,
    img: bestSellerOne,
    productName: "The Intended(A Culling of Blood and Magic)",
    price: "1500",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1029,
    img: bestSellerTwo,
    productName: "Hunger games the ballad of songbirds and snakes",
    price: "1500",
    color: "Gray",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1030,
    img: bestSellerThree,
    productName: "The Wise Man's Fear",
    price: "1500",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1031,
    img: bestSellerFour,
    productName: "Serafina and the Black Cloak",
    price: "1500",
    color: "Black",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1032,
    img: newArrOne,
    productName: "The Intended(A Culling of Blood and Magic)",
    price: "1500",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1033,
    img: newArrTwo,
    productName: "Hunger games the ballad of songbirds and snakes",
    price: "1500",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1034,
    img: newArrThree,
    productName: "The Intended(A Culling of Blood and Magic)",
    price: "1500",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1035,
    img: newArrFour,
    productName: "Serafina and the Black Cloak",
    price: "1500",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1036,
    img: newArrTwo,
    productName: "The Wise Man's Fear",
    price: "1500",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1037,
    img: newArrFour,
    productName: "The Intended(A Culling of Blood and Magic)",
    price: "1500",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1038,
    img: newArrTwo,
    productName: "Hunger games the ballad of songbirds and snakes",
    price: "1500",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1039,
    img: bestSellerFour,
    productName: "Serafina and the Black Cloak",
    price: "1500",
    color: "Black",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1040,
    img: newArrOne,
    productName: "Hunger games the ballad of songbirds and snakes",
    price: "1500",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1041,
    img: newArrTwo,
    productName: "The Intended(A Culling of Blood and Magic)",
    price: "1500",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1042,
    img: newArrThree,
    productName: "Signa Unisex Eyeglasses",
    price: "1500",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1043,
    img: spfThree,
    productName: "Serafina and the Black Cloak",
    price: "1500",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1044,
    img: spfFour,
    productName: "Hunger games the ballad of songbirds and snakes",
    price: "1500",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1045,
    img: bestSellerOne,
    productName: "The Intended(A Culling of Blood and Magic)",
    price: "1400",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1046,
    img: spfOne,
    productName: "Serafina and the Black Cloak",
    price: "1800",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];
// =================== PaginationItems End here =================
